spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stickers
    username: stickers
    password: stickers

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false # To annoying disable INFO error log (nothing serious)
